# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Visually indicate a mop attack
class MopAction(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 2

    # MopAction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MopAction
    def Loc(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateMopAction(builder, loc):
    builder.Prep(2, 2)
    builder.PrependUint16(loc)
    return builder.Offset()
