# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A single time-step in a Game, which contains a list of robot turns
class Round(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Round()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRound(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Round
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The IDs of teams in the Game.
    # Round
    def TeamIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def TeamIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def TeamIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def TeamIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # The total amount of resource this round per team
    # Round
    def TeamResourceAmounts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def TeamResourceAmountsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def TeamResourceAmountsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def TeamResourceAmountsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Ordered turn data for each robot during the round
    # Round
    def Turns(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from battlecode.schema.Turn import Turn
            obj = Turn()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Round
    def TurnsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def TurnsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # The IDs of bodies that died.
    # Round
    def DiedIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def DiedIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def DiedIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def DiedIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # The first sent Round in a match should have index 1. (The starting state,
    # created by the MatchHeader, can be thought to have index 0.)
    # It should increase by one for each following round.
    # Round
    def RoundId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def RoundStart(builder):
    builder.StartObject(5)

def Start(builder):
    RoundStart(builder)

def RoundAddTeamIds(builder, teamIds):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(teamIds), 0)

def AddTeamIds(builder, teamIds):
    RoundAddTeamIds(builder, teamIds)

def RoundStartTeamIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTeamIdsVector(builder, numElems):
    return RoundStartTeamIdsVector(builder, numElems)

def RoundAddTeamResourceAmounts(builder, teamResourceAmounts):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(teamResourceAmounts), 0)

def AddTeamResourceAmounts(builder, teamResourceAmounts):
    RoundAddTeamResourceAmounts(builder, teamResourceAmounts)

def RoundStartTeamResourceAmountsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTeamResourceAmountsVector(builder, numElems):
    return RoundStartTeamResourceAmountsVector(builder, numElems)

def RoundAddTurns(builder, turns):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(turns), 0)

def AddTurns(builder, turns):
    RoundAddTurns(builder, turns)

def RoundStartTurnsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTurnsVector(builder, numElems):
    return RoundStartTurnsVector(builder, numElems)

def RoundAddDiedIds(builder, diedIds):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(diedIds), 0)

def AddDiedIds(builder, diedIds):
    RoundAddDiedIds(builder, diedIds)

def RoundStartDiedIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDiedIdsVector(builder, numElems):
    return RoundStartDiedIdsVector(builder, numElems)

def RoundAddRoundId(builder, roundId):
    builder.PrependInt32Slot(4, roundId, 0)

def AddRoundId(builder, roundId):
    RoundAddRoundId(builder, roundId)

def RoundEnd(builder):
    return builder.EndObject()

def End(builder):
    return RoundEnd(builder)
