# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Turn(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Turn()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTurn(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Turn
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Turn
    def RobotId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Turn
    def Health(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Turn
    def Paint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Turn
    def MoveCooldown(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Turn
    def ActionCooldown(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Turn
    def BytecodesUsed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Turn
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Turn
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Turn
    def ActionsType(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Turn
    def ActionsTypeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Turn
    def ActionsTypeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Turn
    def ActionsTypeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # Turn
    def Actions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x -= self._tab.Pos
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, x)
            return obj
        return None

    # Turn
    def ActionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Turn
    def ActionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

def TurnStart(builder):
    builder.StartObject(10)

def Start(builder):
    TurnStart(builder)

def TurnAddRobotId(builder, robotId):
    builder.PrependInt32Slot(0, robotId, 0)

def AddRobotId(builder, robotId):
    TurnAddRobotId(builder, robotId)

def TurnAddHealth(builder, health):
    builder.PrependInt32Slot(1, health, 0)

def AddHealth(builder, health):
    TurnAddHealth(builder, health)

def TurnAddPaint(builder, paint):
    builder.PrependInt32Slot(2, paint, 0)

def AddPaint(builder, paint):
    TurnAddPaint(builder, paint)

def TurnAddMoveCooldown(builder, moveCooldown):
    builder.PrependInt32Slot(3, moveCooldown, 0)

def AddMoveCooldown(builder, moveCooldown):
    TurnAddMoveCooldown(builder, moveCooldown)

def TurnAddActionCooldown(builder, actionCooldown):
    builder.PrependInt32Slot(4, actionCooldown, 0)

def AddActionCooldown(builder, actionCooldown):
    TurnAddActionCooldown(builder, actionCooldown)

def TurnAddBytecodesUsed(builder, bytecodesUsed):
    builder.PrependInt32Slot(5, bytecodesUsed, 0)

def AddBytecodesUsed(builder, bytecodesUsed):
    TurnAddBytecodesUsed(builder, bytecodesUsed)

def TurnAddX(builder, x):
    builder.PrependUint8Slot(6, x, 0)

def AddX(builder, x):
    TurnAddX(builder, x)

def TurnAddY(builder, y):
    builder.PrependUint8Slot(7, y, 0)

def AddY(builder, y):
    TurnAddY(builder, y)

def TurnAddActionsType(builder, actionsType):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(actionsType), 0)

def AddActionsType(builder, actionsType):
    TurnAddActionsType(builder, actionsType)

def TurnStartActionsTypeVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartActionsTypeVector(builder, numElems):
    return TurnStartActionsTypeVector(builder, numElems)

def TurnAddActions(builder, actions):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(actions), 0)

def AddActions(builder, actions):
    TurnAddActions(builder, actions)

def TurnStartActionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartActionsVector(builder, numElems):
    return TurnStartActionsVector(builder, numElems)

def TurnEnd(builder):
    return builder.EndObject()

def End(builder):
    return TurnEnd(builder)
