// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Generic action representing damage to a robot
 */
export class DamageAction {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DamageAction {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

id():number {
  return this.bb!.readUint16(this.bb_pos);
}

damage():number {
  return this.bb!.readUint16(this.bb_pos + 2);
}

static sizeOf():number {
  return 4;
}

static createDamageAction(builder:flatbuffers.Builder, id: number, damage: number):flatbuffers.Offset {
  builder.prep(2, 4);
  builder.writeInt16(damage);
  builder.writeInt16(id);
  return builder.offset();
}

}
