// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GameplayConstants {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GameplayConstants {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGameplayConstants(bb:flatbuffers.ByteBuffer, obj?:GameplayConstants):GameplayConstants {
  return (obj || new GameplayConstants()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGameplayConstants(bb:flatbuffers.ByteBuffer, obj?:GameplayConstants):GameplayConstants {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GameplayConstants()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startGameplayConstants(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endGameplayConstants(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGameplayConstants(builder:flatbuffers.Builder):flatbuffers.Offset {
  GameplayConstants.startGameplayConstants(builder);
  return GameplayConstants.endGameplayConstants(builder);
}
}
