// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Update the indicator dot for this robot
 */
export class IndicatorDotAction {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):IndicatorDotAction {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

loc():number {
  return this.bb!.readUint16(this.bb_pos);
}

colorHex():number {
  return this.bb!.readInt32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createIndicatorDotAction(builder:flatbuffers.Builder, loc: number, colorHex: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeInt32(colorHex);
  builder.pad(2);
  builder.writeInt16(loc);
  return builder.offset();
}

}
