// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Update the indicator string for this robot
 */
export class IndicatorStringAction {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):IndicatorStringAction {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsIndicatorStringAction(bb:flatbuffers.ByteBuffer, obj?:IndicatorStringAction):IndicatorStringAction {
  return (obj || new IndicatorStringAction()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsIndicatorStringAction(bb:flatbuffers.ByteBuffer, obj?:IndicatorStringAction):IndicatorStringAction {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new IndicatorStringAction()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value():string|null
value(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
value(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startIndicatorStringAction(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, valueOffset, 0);
}

static endIndicatorStringAction(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createIndicatorStringAction(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  IndicatorStringAction.startIndicatorStringAction(builder);
  IndicatorStringAction.addValue(builder, valueOffset);
  return IndicatorStringAction.endIndicatorStringAction(builder);
}
}
