// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum RobotType {
  NONE = 0,
  PAINT_TOWER = 1,
  MONEY_TOWER = 2,
  DEFENSE_TOWER = 3,
  SOLDIER = 4,
  SPLASHER = 5,
  MOPPER = 6
}
