// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum WinType {
  RESIGNATION = 0,
  MAJORITY_PAINTED = 1,
  AREA_PAINTED = 2,
  MORE_TOWERS = 3,
  MORE_MONEY = 4,
  MORE_STORED_PAINT = 5,
  MORE_ROBOTS = 6,
  COIN_FLIP = 7
}
