"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.BuildAction = void 0;
/**
 * Visually indicate a tower being built
 */
var BuildAction = /** @class */ (function () {
    function BuildAction() {
        this.bb = null;
        this.bb_pos = 0;
    }
    BuildAction.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    BuildAction.prototype.id = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    BuildAction.sizeOf = function () {
        return 2;
    };
    BuildAction.createBuildAction = function (builder, id) {
        builder.prep(2, 2);
        builder.writeInt16(id);
        return builder.offset();
    };
    return BuildAction;
}());
exports.BuildAction = BuildAction;
