"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageAction = void 0;
/**
 * Visually indicate messaging from one robot to another
 */
var MessageAction = /** @class */ (function () {
    function MessageAction() {
        this.bb = null;
        this.bb_pos = 0;
    }
    MessageAction.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    MessageAction.prototype.id = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    MessageAction.prototype.data = function () {
        return this.bb.readInt32(this.bb_pos + 4);
    };
    MessageAction.sizeOf = function () {
        return 8;
    };
    MessageAction.createMessageAction = function (builder, id, data) {
        builder.prep(4, 8);
        builder.writeInt32(data);
        builder.pad(2);
        builder.writeInt16(id);
        return builder.offset();
    };
    return MessageAction;
}());
exports.MessageAction = MessageAction;
