"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.MopAction = void 0;
/**
 * Visually indicate a mop attack
 */
var MopAction = /** @class */ (function () {
    function MopAction() {
        this.bb = null;
        this.bb_pos = 0;
    }
    MopAction.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    MopAction.prototype.loc = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    MopAction.sizeOf = function () {
        return 2;
    };
    MopAction.createMopAction = function (builder, loc) {
        builder.prep(2, 2);
        builder.writeInt16(loc);
        return builder.offset();
    };
    return MopAction;
}());
exports.MopAction = MopAction;
