"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.RobotType = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var RobotType;
(function (RobotType) {
    RobotType[RobotType["NONE"] = 0] = "NONE";
    RobotType[RobotType["PAINT_TOWER"] = 1] = "PAINT_TOWER";
    RobotType[RobotType["MONEY_TOWER"] = 2] = "MONEY_TOWER";
    RobotType[RobotType["DEFENSE_TOWER"] = 3] = "DEFENSE_TOWER";
    RobotType[RobotType["SOLDIER"] = 4] = "SOLDIER";
    RobotType[RobotType["SPLASHER"] = 5] = "SPLASHER";
    RobotType[RobotType["MOPPER"] = 6] = "MOPPER";
})(RobotType || (exports.RobotType = RobotType = {}));
