"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferAction = void 0;
/**
 * Visually indicate trasnferring paint from one robot to another
 */
var TransferAction = /** @class */ (function () {
    function TransferAction() {
        this.bb = null;
        this.bb_pos = 0;
    }
    TransferAction.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    TransferAction.prototype.id = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    TransferAction.sizeOf = function () {
        return 2;
    };
    TransferAction.createTransferAction = function (builder, id) {
        builder.prep(2, 2);
        builder.writeInt16(id);
        return builder.offset();
    };
    return TransferAction;
}());
exports.TransferAction = TransferAction;
