"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpgradeAction = void 0;
/**
 * Visually indicate that a tower was upgraded
 */
var UpgradeAction = /** @class */ (function () {
    function UpgradeAction() {
        this.bb = null;
        this.bb_pos = 0;
    }
    UpgradeAction.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    UpgradeAction.prototype.id = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    UpgradeAction.sizeOf = function () {
        return 2;
    };
    UpgradeAction.createUpgradeAction = function (builder, id) {
        builder.prep(2, 2);
        builder.writeInt16(id);
        return builder.offset();
    };
    return UpgradeAction;
}());
exports.UpgradeAction = UpgradeAction;
