# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RobotTypeMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RobotTypeMetadata()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRobotTypeMetadata(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RobotTypeMetadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RobotTypeMetadata
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # RobotTypeMetadata
    def ActionCooldown(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RobotTypeMetadata
    def MovementCooldown(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RobotTypeMetadata
    def BaseHealth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RobotTypeMetadata
    def ActionRadiusSquared(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RobotTypeMetadata
    def VisionRadiusSquared(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RobotTypeMetadata
    def BytecodeLimit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def RobotTypeMetadataStart(builder):
    builder.StartObject(7)

def Start(builder):
    RobotTypeMetadataStart(builder)

def RobotTypeMetadataAddType(builder, type):
    builder.PrependInt8Slot(0, type, 0)

def AddType(builder, type):
    RobotTypeMetadataAddType(builder, type)

def RobotTypeMetadataAddActionCooldown(builder, actionCooldown):
    builder.PrependInt32Slot(1, actionCooldown, 0)

def AddActionCooldown(builder, actionCooldown):
    RobotTypeMetadataAddActionCooldown(builder, actionCooldown)

def RobotTypeMetadataAddMovementCooldown(builder, movementCooldown):
    builder.PrependInt32Slot(2, movementCooldown, 0)

def AddMovementCooldown(builder, movementCooldown):
    RobotTypeMetadataAddMovementCooldown(builder, movementCooldown)

def RobotTypeMetadataAddBaseHealth(builder, baseHealth):
    builder.PrependInt32Slot(3, baseHealth, 0)

def AddBaseHealth(builder, baseHealth):
    RobotTypeMetadataAddBaseHealth(builder, baseHealth)

def RobotTypeMetadataAddActionRadiusSquared(builder, actionRadiusSquared):
    builder.PrependInt32Slot(4, actionRadiusSquared, 0)

def AddActionRadiusSquared(builder, actionRadiusSquared):
    RobotTypeMetadataAddActionRadiusSquared(builder, actionRadiusSquared)

def RobotTypeMetadataAddVisionRadiusSquared(builder, visionRadiusSquared):
    builder.PrependInt32Slot(5, visionRadiusSquared, 0)

def AddVisionRadiusSquared(builder, visionRadiusSquared):
    RobotTypeMetadataAddVisionRadiusSquared(builder, visionRadiusSquared)

def RobotTypeMetadataAddBytecodeLimit(builder, bytecodeLimit):
    builder.PrependInt32Slot(6, bytecodeLimit, 0)

def AddBytecodeLimit(builder, bytecodeLimit):
    RobotTypeMetadataAddBytecodeLimit(builder, bytecodeLimit)

def RobotTypeMetadataEnd(builder):
    return builder.EndObject()

def End(builder):
    return RobotTypeMetadataEnd(builder)
