// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class Action {
  private Action() { }
  public static final byte NONE = 0;
  public static final byte DamageAction = 1;
  public static final byte PaintAction = 2;
  public static final byte UnpaintAction = 3;
  public static final byte AttackAction = 4;
  public static final byte MopAction = 5;
  public static final byte BuildAction = 6;
  public static final byte TransferAction = 7;
  public static final byte MessageAction = 8;
  public static final byte SpawnAction = 9;
  public static final byte UpgradeAction = 10;
  public static final byte IndicatorStringAction = 11;
  public static final byte IndicatorDotAction = 12;
  public static final byte IndicatorLineAction = 13;

  public static final String[] names = { "NONE", "DamageAction", "PaintAction", "UnpaintAction", "AttackAction", "MopAction", "BuildAction", "TransferAction", "MessageAction", "SpawnAction", "UpgradeAction", "IndicatorStringAction", "IndicatorDotAction", "IndicatorLineAction", };

  public static String name(int e) { return names[e]; }
}

