// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class InitialBodyTable extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static InitialBodyTable getRootAsInitialBodyTable(ByteBuffer _bb) { return getRootAsInitialBodyTable(_bb, new InitialBodyTable()); }
  public static InitialBodyTable getRootAsInitialBodyTable(ByteBuffer _bb, InitialBodyTable obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public InitialBodyTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int robotIds(int j) { int o = __offset(4); return o != 0 ? bb.getInt(__vector(o) + j * 4) : 0; }
  public int robotIdsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public IntVector robotIdsVector() { return robotIdsVector(new IntVector()); }
  public IntVector robotIdsVector(IntVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer robotIdsAsByteBuffer() { return __vector_as_bytebuffer(4, 4); }
  public ByteBuffer robotIdsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 4); }
  public battlecode.schema.SpawnAction spawnActions(int j) { return spawnActions(new battlecode.schema.SpawnAction(), j); }
  public battlecode.schema.SpawnAction spawnActions(battlecode.schema.SpawnAction obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o) + j * 6, bb) : null; }
  public int spawnActionsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public battlecode.schema.SpawnAction.Vector spawnActionsVector() { return spawnActionsVector(new battlecode.schema.SpawnAction.Vector()); }
  public battlecode.schema.SpawnAction.Vector spawnActionsVector(battlecode.schema.SpawnAction.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 6, bb) : null; }

  public static int createInitialBodyTable(FlatBufferBuilder builder,
      int robotIdsOffset,
      int spawnActionsOffset) {
    builder.startTable(2);
    InitialBodyTable.addSpawnActions(builder, spawnActionsOffset);
    InitialBodyTable.addRobotIds(builder, robotIdsOffset);
    return InitialBodyTable.endInitialBodyTable(builder);
  }

  public static void startInitialBodyTable(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addRobotIds(FlatBufferBuilder builder, int robotIdsOffset) { builder.addOffset(0, robotIdsOffset, 0); }
  public static int createRobotIdsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startRobotIdsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addSpawnActions(FlatBufferBuilder builder, int spawnActionsOffset) { builder.addOffset(1, spawnActionsOffset, 0); }
  public static void startSpawnActionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(6, numElems, 2); }
  public static int endInitialBodyTable(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public InitialBodyTable get(int j) { return get(new InitialBodyTable(), j); }
    public InitialBodyTable get(InitialBodyTable obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

