// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class RobotType {
  private RobotType() { }
  public static final byte PAINT_TOWER = 0;
  public static final byte MONEY_TOWER = 1;
  public static final byte DEFENSE_TOWER = 2;
  public static final byte SOLDIER = 3;
  public static final byte SPLASHER = 4;
  public static final byte MOPPER = 5;

  public static final String[] names = { "PAINT_TOWER", "MONEY_TOWER", "DEFENSE_TOWER", "SOLDIER", "SPLASHER", "MOPPER", };

  public static String name(int e) { return names[e]; }
}

