// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class WinType {
  private WinType() { }
  public static final byte RESIGNATION = 0;
  public static final byte MAJORITY_PAINTED = 1;
  public static final byte AREA_PAINTED = 2;
  public static final byte MORE_TOWERS = 3;
  public static final byte MORE_MONEY = 4;
  public static final byte MORE_STORED_PAINT = 5;
  public static final byte MORE_ROBOTS = 6;
  public static final byte COIN_FLIP = 7;

  public static final String[] names = { "RESIGNATION", "MAJORITY_PAINTED", "AREA_PAINTED", "MORE_TOWERS", "MORE_MONEY", "MORE_STORED_PAINT", "MORE_ROBOTS", "COIN_FLIP", };

  public static String name(int e) { return names[e]; }
}

