// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class WinType {
  private WinType() { }
  public static final byte AREA_PAINTED = 0;
  public static final byte MORE_TOWERS = 1;
  public static final byte MORE_MONEY = 2;
  public static final byte MORE_STORED_PAINT = 3;
  public static final byte MORE_ROBOTS = 4;
  public static final byte RANDOM = 5;

  public static final String[] names = { "AREA_PAINTED", "MORE_TOWERS", "MORE_MONEY", "MORE_STORED_PAINT", "MORE_ROBOTS", "RANDOM", };

  public static String name(int e) { return names[e]; }
}

