# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class Action(object):
    NONE = 0
    DamageAction = 1
    PaintAction = 2
    UnpaintAction = 3
    AttackAction = 4
    MopAction = 5
    BuildAction = 6
    TransferAction = 7
    MessageAction = 8
    SpawnAction = 9
    UpgradeAction = 10
    DieExceptionAction = 11
    IndicatorStringAction = 12
    IndicatorDotAction = 13
    IndicatorLineAction = 14
