# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class Action(object):
    NONE = 0
    DamageAction = 1
    PaintAction = 2
    UnpaintAction = 3
    MarkAction = 4
    UnmarkAction = 5
    AttackAction = 6
    MopAction = 7
    BuildAction = 8
    TransferAction = 9
    MessageAction = 10
    SpawnAction = 11
    DieAction = 12
    UpgradeAction = 13
    IndicatorStringAction = 14
    IndicatorDotAction = 15
    IndicatorLineAction = 16
