# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class Action(object):
    NONE = 0
    DamageAction = 1
    PaintAction = 2
    UnpaintAction = 3
    MarkAction = 4
    UnmarkAction = 5
    AttackAction = 6
    SplashAction = 7
    MopAction = 8
    BuildAction = 9
    TransferAction = 10
    MessageAction = 11
    SpawnAction = 12
    DieAction = 13
    UpgradeAction = 14
    IndicatorStringAction = 15
    IndicatorDotAction = 16
    IndicatorLineAction = 17
