# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from ..schema.GameplayConstants import GameplayConstants
from ..schema.RobotTypeMetadata import RobotTypeMetadata
from ..schema.TeamData import TeamData
from typing import Optional
np = import_numpy()

# The first event sent in the game. Contains all metadata about the game.
class GameHeader(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GameHeader()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGameHeader(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GameHeader
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GameHeader
    def SpecVersion(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GameHeader
    def Teams(self, j: int) -> Optional[TeamData]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = TeamData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameHeader
    def TeamsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameHeader
    def TeamsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # GameHeader
    def RobotTypeMetadata(self, j: int) -> Optional[RobotTypeMetadata]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = RobotTypeMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameHeader
    def RobotTypeMetadataLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameHeader
    def RobotTypeMetadataIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # GameHeader
    def Constants(self) -> Optional[GameplayConstants]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = GameplayConstants()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def GameHeaderStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    GameHeaderStart(builder)

def GameHeaderAddSpecVersion(builder: flatbuffers.Builder, specVersion: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(specVersion), 0)

def AddSpecVersion(builder: flatbuffers.Builder, specVersion: int):
    GameHeaderAddSpecVersion(builder, specVersion)

def GameHeaderAddTeams(builder: flatbuffers.Builder, teams: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(teams), 0)

def AddTeams(builder: flatbuffers.Builder, teams: int):
    GameHeaderAddTeams(builder, teams)

def GameHeaderStartTeamsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartTeamsVector(builder, numElems: int) -> int:
    return GameHeaderStartTeamsVector(builder, numElems)

def GameHeaderAddRobotTypeMetadata(builder: flatbuffers.Builder, robotTypeMetadata: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(robotTypeMetadata), 0)

def AddRobotTypeMetadata(builder: flatbuffers.Builder, robotTypeMetadata: int):
    GameHeaderAddRobotTypeMetadata(builder, robotTypeMetadata)

def GameHeaderStartRobotTypeMetadataVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartRobotTypeMetadataVector(builder, numElems: int) -> int:
    return GameHeaderStartRobotTypeMetadataVector(builder, numElems)

def GameHeaderAddConstants(builder: flatbuffers.Builder, constants: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(constants), 0)

def AddConstants(builder: flatbuffers.Builder, constants: int):
    GameHeaderAddConstants(builder, constants)

def GameHeaderEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return GameHeaderEnd(builder)
