# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# The final event sent in the game.
class GameFooter(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GameFooter()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGameFooter(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GameFooter
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The ID of the winning team of the game.
    # GameFooter
    def Winner(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def GameFooterStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    GameFooterStart(builder)

def GameFooterAddWinner(builder: flatbuffers.Builder, winner: int):
    builder.PrependInt8Slot(0, winner, 0)

def AddWinner(builder: flatbuffers.Builder, winner: int):
    GameFooterAddWinner(builder, winner)

def GameFooterEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return GameFooterEnd(builder)
