from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class UpgradeAction(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> int: ...
  def NewHealth(self) -> int: ...
  def NewMaxHealth(self) -> int: ...
  def NewPaint(self) -> int: ...
  def NewMaxPaint(self) -> int: ...

def CreateUpgradeAction(builder: flatbuffers.Builder, id: int, newHealth: int, newMaxHealth: int, newPaint: int, newMaxPaint: int) -> uoffset: ...

