# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class WinType(object):
    RESIGNATION = 0
    MAJORITY_PAINTED = 1
    ALL_UNITS_DESTROYED = 2
    AREA_PAINTED = 3
    MORE_TOWERS = 4
    MORE_MONEY = 5
    MORE_STORED_PAINT = 6
    MORE_ROBOTS = 7
    COIN_FLIP = 8
