# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb_schema

class RobotType(object):
    NONE = 0
    PAINT_TOWER = 1
    MONEY_TOWER = 2
    DEFENSE_TOWER = 3
    SOLDIER = 4
    SPLASHER = 5
    MOPPER = 6
